server:
  servlet:
    context-path: /image-upload
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imageupload
    username: postgres
    password: Sangi@123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
springdoc:
  group-configs:
    - group: com.example
      packagesToScan:
        - "com.image.upload"
  swagger-ui:
    path: /img-001-swagger-ui.html
  api-docs:
    path: /v3/img-001-api-docs

